package gov.va.athena.advisory.impl;

import java.util.*;

import gov.va.athena.advisory.*;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Add_Delete_Drug_Recommendation
 *
 * @version generated on Wed Jun 06 18:58:08 GMT 2012
 */
public class DefaultAdd_Delete_Drug_Recommendation extends DefaultDrug_Recommendation implements Add_Delete_Drug_Recommendation {

    /* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime
				* result
				+ ((associated_substitution_drug == null) ? 0
						: associated_substitution_drug.hashCode());
		result = prime * result
				+ ((drug_class == null) ? 0 : drug_class.hashCode());
		result = prime
				* result
				+ ((drug_to_add_string == null) ? 0 : drug_to_add_string
						.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (!super.equals(obj)) {
			return false;
		}
		if (!(obj instanceof DefaultAdd_Delete_Drug_Recommendation)) {
			return false;
		}
		DefaultAdd_Delete_Drug_Recommendation other = (DefaultAdd_Delete_Drug_Recommendation) obj;
		if (associated_substitution_drug == null) {
			if (other.associated_substitution_drug != null) {
				return false;
			}
		} else if (!associated_substitution_drug
				.equals(other.associated_substitution_drug)) {
			return false;
		}
		if (drug_class == null) {
			if (other.drug_class != null) {
				return false;
			}
		} else if (!drug_class.equals(other.drug_class)) {
			return false;
		}
		if (drug_to_add_string == null) {
			if (other.drug_to_add_string != null) {
				return false;
			}
		} else if (!drug_to_add_string.equals(other.drug_to_add_string)) {
			return false;
		}
		return true;
	}

	protected Add_Delete_Drug_Recommendation associated_substitution_drug = null;
    protected String drug_class = null;
    protected Collection<Evaluated_Drug_Relation> evaluated_drug_relation = new ArrayList();
    protected String rule_in_criteria = null;
    protected String drug_to_add_string = null;

    public DefaultAdd_Delete_Drug_Recommendation() {
    }

    // Slot associated_substitution_drug
    public Add_Delete_Drug_Recommendation getAssociated_substitution_drug() {
        return associated_substitution_drug;
    }

    public boolean hasAssociated_substitution_drug() {
        return associated_substitution_drug != null;
    }

    public void setAssociated_substitution_drug(Add_Delete_Drug_Recommendation newAssociated_substitution_drug) {
        associated_substitution_drug = newAssociated_substitution_drug;
    }

    // Slot drug_class
    public String getDrug_class() {
        return drug_class;
    }

    public boolean hasDrug_class() {
        return drug_class != null;
    }

    public void setDrug_class(String newDrug_class) {
        drug_class = newDrug_class;
    }

    // Slot drug_to_add_string
    public String getDrug_to_add_string() {
        return drug_to_add_string;
    }

    public boolean hasDrug_to_add_string() {
        return drug_to_add_string != null;
    }

    public void setDrug_to_add_string(String newDrug_to_add_string) {
        drug_to_add_string = newDrug_to_add_string;
    }
    // Slot evaluated_drug_relation

    public Collection<Evaluated_Drug_Relation> getEvaluated_drug_relation() {
        if (evaluated_drug_relation.isEmpty()) {
            return null;
        } else {
            return evaluated_drug_relation;
        }
    }

    public boolean hasEvaluated_drug_relation() {
        return !evaluated_drug_relation.isEmpty();
    }

    public void addEvaluated_drug_relation(Evaluated_Drug_Relation newEvaluated_drug_relation) {
        evaluated_drug_relation.add(newEvaluated_drug_relation);
    }

    public void removeEvaluated_drug_relation(Evaluated_Drug_Relation oldEvaluated_drug_relation) {
        evaluated_drug_relation.remove(oldEvaluated_drug_relation);
    }

    public void setEvaluated_drug_relation(Collection<? extends Evaluated_Drug_Relation> newEvaluated_drug_relation) {
        evaluated_drug_relation.addAll(newEvaluated_drug_relation);
    }

    // Slot rule_in_criteria
    public String getRule_in_criteria() {
        return rule_in_criteria;
    }

    public boolean hasRule_in_criteria() {
        return rule_in_criteria != null;
    }

    public void setRule_in_criteria(String newRule_in_criteria) {
        rule_in_criteria = newRule_in_criteria;
    }
    
    public boolean equals(Add_Delete_Drug_Recommendation anAddDelRec) {     
      boolean result = super.equals((Drug_Recommendation) anAddDelRec);
      if (result == false) return false;
      
      // No drug_to_add_string name for either drug rec, or both, means these drug recommendations
      // can't be equal
      if (drug_to_add_string == null || anAddDelRec.getDrug_to_add_string() == null)
         return false;
      
      if (drug_class.equals(anAddDelRec.getDrug_class()) &&
          drug_to_add_string.equals(anAddDelRec.getDrug_to_add_string()) )
        return true;
      else
        return false;
      
    }    
}
