package gov.va.athena.advisory.impl;

import gov.va.athena.advisory.Conclusion;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Conclusion
 *
 * @version generated on Wed Jun 06 18:58:08 GMT 2012
 */
public class DefaultConclusion extends DefaultAdvisory_Component implements Conclusion {
    protected String parameter = null;
    protected String value = null;

    public DefaultConclusion() {
    }


    // Slot parameter

    public String getParameter() {
        return parameter;  }


    public boolean hasParameter() {
        return parameter != null;
    }


    public void setParameter(String newParameter) {
    	parameter = newParameter;
    }

    // Slot value

    public String getValue() {
        return value; }


    public boolean hasValue() {
        return value != null;
    }


    public void setValue(String newValue) {
    	value = newValue;
    }
}
