package gov.va.athena.advisory.impl;

import gov.va.athena.advisory.Missing_Data;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Conclusion
 *
 * @version generated on Wed Jun 06 18:58:08 GMT 2012
 */
public class DefaultMissing_Data extends DefaultAdvisory_Component implements Missing_Data {

    protected String criterion_id = null;
    protected String parameter = null;
    protected String evaluation_result = null; 

    public DefaultMissing_Data() {
    }
    // Slot criterion_id
    public String getCriterion_id() {
        return criterion_id;
    }

    public boolean hasCriterion_id() {
        return criterion_id != null;
    }

    public void setCriterion_id(String newCriterion_id) {
        criterion_id = newCriterion_id;
    }
    

    
    // Slot criterion_evaluation_result (can be true,false,unknown)
    // In addition, for performance measures, 
    //   if criterion type = denominator,  
    //        criterion_evaluation_result = false (for exclusion)
    //   if criterion type = exclusion
    //        criterion_evaluation_result = true (for exclusion)    
    public String getCriterion_evaluation_result() {
        return evaluation_result;
    }
    public boolean hasCriterion_evaluation_result() {
        return evaluation_result != null;
    }
    public void setCriterion_evaluation_result(String newEvaluation_result){
        evaluation_result = newEvaluation_result;
    }            
    
    // Slot parameter

    public String getParameter() {
        return parameter;
    }

    public boolean hasParameter() {
        return parameter != null;
    }

    public void setParameter(String newParameter) {
        parameter = newParameter;
    }    

    
}
