package gov.va.athena.advisory.impl;

import java.util.*;

import gov.va.athena.advisory.Evaluated_Drug_Relation;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Evaluated_Drug_Relation
 *
 * @version generated on Wed Jun 06 18:58:08 GMT 2012
 */
public class DefaultEvaluated_Drug_Relation extends DefaultAdvisory_Component implements Evaluated_Drug_Relation {
    protected String condition_or_drug = null;
    protected String substance = null;
    protected Collection<String> reference = new ArrayList();
    protected String relation_type = null;

    public DefaultEvaluated_Drug_Relation() {
    }


    // Slot condition_or_drug

    public String getCondition_or_drug() {
        return 	condition_or_drug;
}


    public boolean hasCondition_or_drug() {
        return condition_or_drug != null;
    }


    public void setCondition_or_drug(String newCondition_or_drug) {
    	condition_or_drug= newCondition_or_drug;
    }
    
    // Slot substance (only useful for adverse reactions, where it is the drug or ingredient
    // which causes a reaction, which is captured in condition_or_drug
    public String getSubstance() {
      return substance;    
    }    
    public boolean hasSubstance() {
      return substance != null;        
    }
    public void setSubstance(String aSubstance) {
      substance = aSubstance;
    }       


    // Slot reference

    public Collection<String> getReference() {
        if (reference.isEmpty()) return null;
        else return reference;
    }


    public boolean hasReference() {
        return !reference.isEmpty();
    }


    public void addReference(String newReference) {
    	reference.add(newReference);
    }


    public void removeReference(String oldReference) {
    	reference.remove(oldReference);
    }


    public void setReference(Collection<String> newReference) {
    	reference.addAll(newReference);
    }

    // Slot relation_type

    public String getRelation_type() {
        return relation_type;  }


    public boolean hasRelation_type() {
        return relation_type != null;
    }


    public void setRelation_type(String newRelation_type) {
    	relation_type =newRelation_type;
    }
}
