package gov.va.athena.advisory.impl;

import gov.va.athena.advisory.Exclusion;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Conclusion
 *
 * @version generated on Wed Jun 06 18:58:08 GMT 2012
 */
public class DefaultExclusion extends DefaultAdvisory_Component implements Exclusion {
    protected String criterion_id = null;
    protected String criterion_type = null;
    protected String kb_goal_id = null;
    protected String data = null;
    protected String criterion_evaluation_result = null;

    public DefaultExclusion() {
    }
    // Slot criterion_id

    public String getCriterion_id() {
        return criterion_id;
    }

    public boolean hasCriterion_id() {
        return criterion_id != null;
    }

    public void setCriterion_id(String newCriterion_id) {
        criterion_id = newCriterion_id;
    }
    
    // Slot kb_goal_id

    public String getKb_goal_id() {
        return kb_goal_id;
    }

    public boolean hasKb_goal_id() {
        return kb_goal_id != null;
    }

    public void setKb_goal_id(String newKb_goal_id) {
        kb_goal_id = newKb_goal_id;
    }   
    
    // Slot criterion_type

    public String getCriterion_type() {
        return criterion_type;
    }

    public boolean hasCriterion_type() {
        return criterion_type != null;
    }

    public void setCriterion_type(String newCriterion_type) {
        criterion_type = newCriterion_type;
    }
    
    // Slot criterion_evaluation_result (can be true,false,unknown)
    // In addition, for performance measures, 
    //   if criterion type = denominator,  
    //        criterion_evaluation_result = false (for exclusion)
    //   if criterion type = exclusion
    //        criterion_evaluation_result = true (for exclusion)
    public String getCriterion_evaluation_result() {
        return criterion_evaluation_result;
    }

    public boolean hasCriterion_evaluation_result() {
        return criterion_evaluation_result != null;
    }

    public void setCriterion_evaluation_result(String newCriterion_evaluation_result){
        criterion_evaluation_result = newCriterion_evaluation_result;
    }            
    
    // Slot data

    public String getData() {
        return data;
    }

    public boolean hasData() {
        return data != null;
    }

    public void setData(String newData) {
        data = newData;
    }    

    
}
