package gov.va.athena.advisory.impl;

import java.util.*;

import gov.va.athena.advisory.Criterion_Evaluation;
import gov.va.athena.advisory.Action;
import gov.va.athena.advisory.Guideline_Goal;


/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Guideline_Goal
 *
 * @version generated on Wed Jun 06 18:58:08 GMT 2012
 */
public class DefaultGuideline_Goal extends DefaultAdvisory_Component implements Guideline_Goal {

    protected String goal = null;
    protected String achieved = null;
    protected String kb_goal_id = null;       //for performance measures; the conditional_goal
                                              //corresponding to the performance measure
    protected String reason_for_goal = null;
    protected String data = null;
    protected Collection<Action> collaterol_action = new ArrayList();
    protected int fine_grain_priority = 0;
    protected boolean isPrimary = true;
    protected Collection<Criterion_Evaluation> listCriterion_Evaluation = new ArrayList();    
    

    public DefaultGuideline_Goal() {
    }

    // Slot achieved

    public String getAchieved() {
        return achieved;
    }

    public boolean hasAchieved() {
        return achieved != null;
    }

    public void setAchieved(String newAchieved) {
    	achieved = newAchieved;
    }

    // Slot kb_goal_id

    public String getKb_goal_id() {
        return kb_goal_id;
    }

    public boolean hasKb_goal_id() {
        return kb_goal_id != null;
    }

    public void setKb_goal_id(String newKb_goal_id) {
        kb_goal_id = newKb_goal_id;
    }

    // Slot goal

    public String getGoal() {
        return goal;
    }

    public boolean hasGoal() {
        return goal != null;
    }

    public void setGoal(String newGoal) {
    	goal =newGoal;
    }

    // Slot reason_for_goal

    public String getReason_for_goal() {
        return reason_for_goal;
    }

    public boolean hasReason_for_goal() {
    	return reason_for_goal != null;
    }

    public void setReason_for_goal(String newReason_for_goal) {
    	reason_for_goal = newReason_for_goal;
    }

    // Slot source

    public String getData() {
    	return data;
    }

    public boolean hasData() {
    	return (data != null);
    }

    public void setData(String newData) {
    	data = newData;
    }

    // Slot messages

    public Collection<Action> getCollaterol_action() {
        if (collaterol_action.isEmpty()) return null;
        else return collaterol_action;
    }

    public boolean hasCollaterol_action() {
        return !collaterol_action.isEmpty();
    }

    public void addCollaterol_action(Action newCollaterol_action) {
    	collaterol_action.add(newCollaterol_action);
    }

    public void removeCollaterol_action(Action oldCollaterol_action) {
    	collaterol_action.remove(oldCollaterol_action);
    }

    public void setCollaterol_action(Collection<Action> listCollaterol_action) {
    	collaterol_action.addAll(listCollaterol_action);
    }
    
    // Slot criteria_evaluation

    public Collection<Criterion_Evaluation> getCriterion_Evaluation() {
        if (listCriterion_Evaluation.isEmpty()) return null;
        else return listCriterion_Evaluation;
    }

    public boolean hasCriterion_Evaluation() {
        return !listCriterion_Evaluation.isEmpty();
    }

    public void addCriterion_Evaluation(Criterion_Evaluation newCriterion_Evaluation) {
    	listCriterion_Evaluation.add(newCriterion_Evaluation);
    }

    public void removeCriterion_Evaluation(Criterion_Evaluation oldCriterion_evaluation) {
    	listCriterion_Evaluation.remove(oldCriterion_evaluation);
    }

    public void setCriterion_Evaluation(Collection<Criterion_Evaluation> newCriteria_Evaluation) {
    	listCriterion_Evaluation.addAll(newCriteria_Evaluation);
    }    

    // Slot fine_grain_priority

    public int getFine_grain_priority() {
        return fine_grain_priority;
    }

    public boolean hasFine_grain_priority() {
        return (fine_grain_priority >= 0);
    }

    public void setFine_grain_priority(int newFine_grain_priority) {
    	fine_grain_priority = newFine_grain_priority;
    }

    public boolean getPrimary() {
            return isPrimary;
    }
    
    public void setPrimary(boolean newPrimary) {
            isPrimary = newPrimary;
    }
}
