package gov.va.athena.advisory.impl;

import gov.va.athena.advisory.Action;

import java.util.*;

import gov.va.athena.advisory.Message;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Message
 *
 * @version generated on Wed Jun 06 18:58:08 GMT 2012
 */
public class DefaultMessage extends DefaultAction implements Message {
    /* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((message == null) ? 0 : message.hashCode());
		result = prime * result
				+ ((message_type == null) ? 0 : message_type.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (!super.equals(obj)) {
			return false;
		}
		if (!(obj instanceof DefaultMessage)) {
			return false;
		}
		DefaultMessage other = (DefaultMessage) obj;
		if (message == null) {
			if (other.message != null) {
				return false;
			}
		} else if (!message.equals(other.message)) {
			return false;
		}
		if (message_type == null) {
			if (other.message_type != null) {
				return false;
			}
		} else if (!message_type.equals(other.message_type)) {
			return false;
		}
		return true;
	}

	protected String message = null;
    protected String message_type = null;
    protected String rule_in_criteria = null;

    public DefaultMessage() {
        fine_grain_priority = -1;
    }

    // Slot fine_grain_priority

    public int getFine_grain_priority() {
        return fine_grain_priority;
    }

    public boolean hasFine_grain_priority() {
        return (fine_grain_priority >= 0);
    }

    public void setFine_grain_priority(int newFine_grain_priority) {
    	fine_grain_priority = newFine_grain_priority;
    }

    // Slot message

    public String getMessage() {
        return message; }

    public boolean hasMessage() {
        return message != null;
    }

    public void setMessage(String newMessage) {
    	message=newMessage;
    }

    // Slot message_type

    public String getMessage_type() {
        return message_type;}

    public boolean hasMessage_type() {
        return message_type != null;
    }

    public void setMessage_type(String newMessage_type) {
    	message_type =newMessage_type;
    }

    // Slot rule_in_criteria

    public String getRule_in_criteria() {
        return rule_in_criteria;   }


    public boolean hasRule_in_criteria() {
        return rule_in_criteria != null;
    }

    public void setRule_in_criteria(String newRule_in_criteria) {
    	rule_in_criteria= newRule_in_criteria;
    }
    
    public boolean equals(Message aMsg)  {
      if (!super.equals( aMsg )) 
        return false;
      if (!message.equals(aMsg.getMessage()) )
        return false;
      return true;
    }      
}
