package gov.va.athena.advisory.impl;

import gov.va.athena.advisory.Advisory_Component;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Advisory_Component
 *
 * @version generated on Wed Jun 06 18:58:08 GMT 2012
 */
public abstract class DefaultAdvisory_Component implements Advisory_Component {

    protected String case_id = null;
    protected String guideline_id = null;

    public DefaultAdvisory_Component() {
    }
}
