package gov.va.athena.advisory;

import java.util.*;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Action
 *
 * @version generated on Thu Jul 05 01:40:52 GMT 2012
 */
public interface Action extends Advisory_Component {
    // Slot action_class

    String getAction_class();

    boolean hasAction_class();

    void setAction_class(String newAction_class);

    // Slot description

    String getDescription();

    boolean hasDescription();

    void setDescription(String newDescription);

    // Slot fine_grain_priority

    int getFine_grain_priority();

    boolean hasFine_grain_priority();

    void setFine_grain_priority(int newFine_grain_priority);

    // Slot grade_recommendation

    String getGrade_recommendation();

    boolean hasGrade_recommendation();

    void setGrade_recommendation(String newGrade_recommendation);

    // Slot label

    String getLabel();

    boolean hasLabel();

    void setLabel(String newLabel);

    // Slot net_benefit

    String getNet_benefit();

    boolean hasNet_benefit();

    void setNet_benefit(String newNet_benefit);

    // Slot overall_quality_evidence

    String getOverall_quality_evidence();

    boolean hasOverall_quality_evidence();

    void setOverall_quality_evidence(String newOverall_quality_evidence);

    // Slot quality_of_evidence

    String getQuality_of_evidence();

    boolean hasQuality_of_evidence();

    void setQuality_of_evidence(String newQuality_of_evidence);

    // Slot reference

    Collection<String> getReference();

    boolean hasReference();

    void addReference(String newReference);

    void removeReference(String oldReference);

    void setReference(Collection<String> newReference);

    // Slot subsidiary_message

    Collection<String> getSubsidiary_message();

    boolean hasSubsidiary_message();

    void addSubsidiary_message(String newSubsidiary_message);

    void removeSubsidiary_message(String oldSubsidiary_message);

    void setSubsidiary_message(Collection<String> newSubsidiary_message);
    
    // Slot Collateral_actions

    Collection<Action> getCollateral_action();

    boolean hasCollateral_action();

    void addCollateral_action(Action newCollateral_action);

    void removeCollateral_action(Action oldCollateral_action);

    void setCollateral_action(Collection<Action> newCollateral_action);


    
    boolean equals(Action anAction);       
    
    public int hashCode() ;
    
    public boolean equals(Object o);

}
