package gov.va.athena.advisory;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Advisory_Component
 *
 * @version generated on Thu Jul 05 01:40:52 GMT 2012
 */
public interface Advisory_Component {

    
}
