package gov.va.athena.advisory;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Conclusion
 *
 * @version generated on Thu Jul 05 01:40:52 GMT 2012
 */
public interface Conclusion extends Advisory_Component {

    // Slot parameter

    String getParameter();

    boolean hasParameter();

    void setParameter(String newParameter);


    // Slot value

    String getValue();

    boolean hasValue();

    void setValue(String newValue);

    
}
