package gov.va.athena.advisory;

import java.util.*;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Drug_Recommendation
 *
 * @version generated on Thu Jul 05 01:40:52 GMT 2012
 */
public interface Drug_Recommendation extends Advisory_Component {

    // Slot drug_action_type

    String getDrug_action_type();

    boolean hasDrug_action_type();

    void setDrug_action_type(String newDrug_action_type);


    // Slot Collateral_actions

    Collection<Action> getCollateral_action();

    boolean hasCollateral_action();

    void addCollateral_action(Action newCollateral_action);

    void removeCollateral_action(Action oldCollateral_action);

    void setCollateral_action(Collection<Action> newCollateral_action);


    // Slot preference

    String getPreference();

    boolean hasPreference();

    void setPreference(String newPreference);

    // Slot fine_grain_priority

    int getFine_grain_priority();

    boolean hasFine_grain_priority();

    void setFine_grain_priority(int newFine_grain_priority);


    // Slot specific_drug

    Collection<String> getSpecific_drug();

    boolean hasSpecific_drug();

    void addSpecific_drug(String newSpecific_drug);

    void removeSpecific_drug(String oldSpecific_drug);

    void setSpecific_drug(Collection<String> newSpecific_drug);

    boolean equals(Drug_Recommendation aDrugRec);
    
    public int hashCode() ;
    
    public boolean equals(Object o);
}
