package gov.va.athena.advisory;

import java.util.*;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Guideline_Goal
 *
 * @version generated on Thu Jul 05 01:40:52 GMT 2012
 */
public interface Guideline_Goal extends Advisory_Component {

    // Slot achieved

    String getAchieved();

    boolean hasAchieved();

    void setAchieved(String newAchieved);


    // Slot data

    String getData();

    boolean hasData();

    void setData(String newData);
    
    // Slot kb_goal_id

    String getKb_goal_id();

    boolean hasKb_goal_id();

    void setKb_goal_id(String newKb_goal_id);    


    // Slot fine_grain_priority

    int getFine_grain_priority();

    boolean hasFine_grain_priority();

    void setFine_grain_priority(int newFine_grain_priority);


    // Slot goal

    String getGoal();

    boolean hasGoal();

    void setGoal(String newGoal);
    
    // Slot Collaterol_action
    public Collection<Action> getCollaterol_action();
    public boolean hasCollaterol_action();
    public void addCollaterol_action(Action newAction);
    public void removeCollaterol_action(Action oldCollaterol_action);
    public void setCollaterol_action(Collection<Action> newAction);    


    // Slot Criterion_Evaluation
    public Collection<Criterion_Evaluation> getCriterion_Evaluation();
    public boolean hasCriterion_Evaluation();
    public void addCriterion_Evaluation(Criterion_Evaluation newCriterion_Evaluation);
    public void removeCriterion_Evaluation(Criterion_Evaluation existingCriterion_Evaluation);
    public void setCriterion_Evaluation(Collection<Criterion_Evaluation> listCriterion_Evaluation);    

    // Slot primary

    boolean getPrimary();
    void setPrimary(boolean newPrimary);

    // Slot reason_for_goal

    String getReason_for_goal();

    boolean hasReason_for_goal();

    void setReason_for_goal(String newReason_for_goal);

}
