package gov.va.athena.advisory;

import java.util.*;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Increase_Decrease_Dose_Recommendation
 *
 * @version generated on Thu Jul 05 01:40:52 GMT 2012
 */
public interface Increase_Decrease_Dose_Recommendation extends Drug_Recommendation {

    // Slot evaluated_drug_relation

    Collection<Evaluated_Drug_Relation> getEvaluated_drug_relation();

    boolean hasEvaluated_drug_relation();

    void addEvaluated_drug_relation(Evaluated_Drug_Relation newEvaluated_drug_relation);

    void removeEvaluated_drug_relation(Evaluated_Drug_Relation oldEvaluated_drug_relation);

    void setEvaluated_drug_relation(Collection<? extends Evaluated_Drug_Relation> newEvaluated_drug_relation);

    boolean equals(Increase_Decrease_Dose_Recommendation anIncDecDoseRec);    
}
